// <auto-generated />
using System;
using LateCheckInApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LateCheckInApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414150844_AddTermsAuditFields")]
    partial class AddTermsAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LateCheckInApp.Models.GuestRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarRego")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DepositAuthorizationAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DepositAuthorizationAcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoIdPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TermsAcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TermsEffectiveFromUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("_guestRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
