// <auto-generated />
using System;
using LateCheckInApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LateCheckInApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416170615_AddPreAuthForAdminPage")]
    partial class AddPreAuthForAdminPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LateCheckInApp.Models.GuestRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarRego")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DepositAuthorizationAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DepositAuthorizationAcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalPaymentStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoIdContentType")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PhotoIdFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoIdOriginalFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoIdPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PhotoIdUploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreAuthAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreAuthCapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreAuthCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreAuthPaymentIntentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreAuthReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreAuthStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignaturePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TermsAcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TermsEffectiveFromUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("_guestRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
